config/routes.rb
QuestionMaster::Application.routes.draw do
  match "test/take/:subject/:size" => 'test#take', as: :test
  match "questions/:id/rate/:difficulty" => 'questions#rate', as: :rate
  match "questions/:id/show" => 'questions#show_answer', as: :show_answer
  resources :subjects

  resources :questions

  root :to => 'subjects#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :count, :subject_id, :difficulty, :answer, :tex
  belongs_to :subject

  def increment
    self.count += 1
    self.save!
  end

  def tex_answer
    "$" + self.answer.gsub(/\n/, '\\\\') + "$"
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name, :tex
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to new_question_path(subject: @question.subject), notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])
    subject_id = @question.subject_id

    respond_to do |format|
      if @question.update_attributes(params[:question])
        @question.subject_id = subject_id
        @question.save!

        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  def rate
    @question = Question.find(params[:id])
    @question.difficulty = params[:difficulty].to_i
    @question.save!

    respond_to do |format|
      format.js
    end
  end
  def show_answer
    @quest_id = params[:id]

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])
    @questions = @subject.questions
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def take
    @subject = Subject.find(params[:subject])
    size = params[:size].to_i || 10
    questions = @subject.questions

    if questions.count > size
      @asked_questions = questions.shuffle.sort_by{|x| x.count}.shift(size * 3)
      @asked_questions = @asked_questions.sort_by{|x| x.difficulty}.shift(size).shuffle
    else
      @asked_questions = questions
    end

    @asked_questions.each{|x| x.increment}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title QuestionMaster
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %script{:src => "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML", :type => "text/javascript"}
    %script{:type => "text/x-mathjax-config"}
      MathJax.Hub.Config({tex2jax:{inlineMath:[['$','$'],['$$','$$']]},"HTML-CSS":{linebreaks:{automatic:true}}})

  %body
    = yield

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content

  .field
    = f.label :answer
    = f.text_area :answer

  .field
    = f.label :tex
    = f.check_box :tex

    = f.hidden_field :subject_id
  .actions
    = f.submit 'Save'

%script=raw("$('#question_subject_id').val('#{params[:subject]}')")

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Content
    %th Count
    %th Subject
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.content
      %td= question.count
      %td= question.subject_id
      %td= link_to 'Show', question
      %td= link_to 'Edit', edit_question_path(question)
      %td= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question
.span8.offset2
  = render 'form'

  = link_to 'Back', questions_path

app/views/questions/rate.js.erb
var element = <%= raw("$('.question-#{@question.id}')")%>;
console.log("updated:" + element);
$(element).hide('slow');

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @question.content
%p
  %b Answer:
  = @question.answer

%p
  %b Count:
  = @question.count
%p
  %b Subject:
  = @question.subject.name

= link_to 'Add another one', new_question_path(subject: @question.subject)

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

app/views/questions/show_answer.js.erb
$("#answer-<%= @quest_id %>").removeClass("hidden");

app/views/subjects/_form.html.haml
= form_for @subject do |f|
  - if @subject.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subject.errors.count, "error")} prohibited this subject from being saved:"
      %ul
        - @subject.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/subjects/edit.html.haml
%h1 Editing subject

= render 'form'

= link_to 'Show', @subject
\|
= link_to 'Back', subjects_path

app/views/subjects/index.html.haml
.row-fluid
  %h1.span2.offset2 Listing subjects
  #subjects.span10.offset1.row-fluid
    - @subjects.each do |subject|
      .span10.offset1.well
        %h2= subject.name
        .btn-group
          .btn
            = link_to 'Test!', test_path(size: 10, subject: subject.id)
          .btn
            = link_to 'Show', subject
          .btn
            = link_to 'Edit', edit_subject_path(subject)
          .btn
            = link_to 'Add Questions', new_question_path(subject: subject)

  = link_to 'New Subject', new_subject_path, :class => "btn btn-primary span2 offset2"

app/views/subjects/new.html.haml
%h1 New subject

= render 'form'

= link_to 'Back', subjects_path

app/views/subjects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @subject.name
  %br
  %b Questions:
  %ul
    -@questions.each do |question|
      %li
        =question.content

= link_to 'Edit', edit_subject_path(@subject)
\|
= link_to 'Back', subjects_path